spring:
  kafka:
    producer:
      bootstrap-servers: 192.168.1.7:9092
  datasource:
    url: jdbc:postgresql://localhost:5432/blood
    username: aliadmin
    password: password
    platform: POSTGRESQL
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
server:
  port: 9095
