spring:
  application:
    name: api-gateway
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/book_db
    username: aliadmin
    password: Mofodamu8!
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
server:
  port: 8082
zuul:
  routes:
    product-api:
      path: /api/**
      service-id: product-server
eureka:
  client:
    service-url:
      defaulZone: http://localhost:8761/eureka
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000